import torch
import gc
import traceback
import sys
from collections import defaultdict
import weakref
import numpy as np
from contextlib import contextmanager

class GPUMemoryInspector:
    """
    Comprehensive GPU memory inspector to find OOM culprits. 
    WARNING: GENERATED BY AI!
    """
    
    def __init__(self, rank=0):
        self.rank = rank
        self.tensor_registry = {}
        self.allocation_history = []
        self.enable_tracking()
    
    def enable_tracking(self):
        """Enable tensor tracking for all new tensors"""
        # Monkey patch tensor creation to track allocations
        original_new = torch.Tensor.__new__
        
        def tracked_new(cls, *args, **kwargs):
            tensor = original_new(cls, *args, **kwargs)
            if tensor.is_cuda:
                self.register_tensor(tensor)
            return tensor
        
        torch.Tensor.__new__ = staticmethod(tracked_new)
    
    def register_tensor(self, tensor):
        """Register a GPU tensor for tracking"""
        tensor_id = id(tensor)
        stack = traceback.extract_stack()
        
        self.tensor_registry[tensor_id] = {
            'shape': tensor.shape,
            'dtype': tensor.dtype,
            'device': tensor.device,
            'size_mb': tensor.numel() * tensor.element_size() / 1e6,
            'creation_stack': stack[-5:],  # Last 5 stack frames
            'weak_ref': weakref.ref(tensor)
        }
        
        self.allocation_history.append({
            'action': 'allocate',
            'tensor_id': tensor_id,
            'size_mb': self.tensor_registry[tensor_id]['size_mb'],
            'total_tensors': len(self.tensor_registry)
        })
    
    def cleanup_dead_refs(self):
        """Clean up references to deleted tensors"""
        dead_ids = []
        for tensor_id, info in self.tensor_registry.items():
            if info['weak_ref']() is None:
                dead_ids.append(tensor_id)
        
        for tensor_id in dead_ids:
            del self.tensor_registry[tensor_id]
    
    def get_all_gpu_tensors(self):
        """Get all tensors currently on GPU"""
        self.cleanup_dead_refs()
        
        live_tensors = []
        for obj in gc.get_objects():
            if isinstance(obj, torch.Tensor) and obj.is_cuda:
                size_mb = obj.numel() * obj.element_size() / 1e6
                live_tensors.append({
                    'id': id(obj),
                    'shape': obj.shape,
                    'dtype': obj.dtype,
                    'device': obj.device,
                    'size_mb': size_mb,
                    'requires_grad': obj.requires_grad,
                    'is_leaf': obj.is_leaf,
                    'grad_fn': str(obj.grad_fn) if obj.grad_fn else None
                })
        
        # Sort by size (largest first)
        live_tensors.sort(key=lambda x: x['size_mb'], reverse=True)
        return live_tensors
    
    def print_gpu_tensor_report(self, top_n=20):
        """Print detailed report of GPU tensors"""
        tensors = self.get_all_gpu_tensors()
        total_size = sum(t['size_mb'] for t in tensors)
        
        print(f"\n{'='*60}")
        print(f"GPU TENSOR REPORT - Rank {self.rank}")
        print(f"{'='*60}")
        print(f"Total Tensors: {len(tensors)}")
        print(f"Total Size: {total_size:.2f} MB")
        print(f"PyTorch Allocated: {torch.cuda.memory_allocated()/1e6:.2f} MB")
        print(f"PyTorch Reserved: {torch.cuda.memory_reserved()/1e6:.2f} MB")
        
        print(f"\nTop {min(top_n, len(tensors))} Largest Tensors:")
        print(f"{'Size (MB)':<12} {'Shape':<25} {'DType':<10} {'Grad':<5} {'GradFn'}")
        print("-" * 80)
        
        for i, tensor in enumerate(tensors[:top_n]):
            grad_info = "Yes" if tensor['requires_grad'] else "No"
            grad_fn = tensor['grad_fn'][:20] if tensor['grad_fn'] else "None"
            shape_str = str(tensor['shape'])[:23]
            
            print(f"{tensor['size_mb']:<12.2f} {shape_str:<25} {str(tensor['dtype']):<10} "
                  f"{grad_info:<5} {grad_fn}")
    
    def find_memory_leaks(self):
        """Find potential memory leaks by analyzing tensor patterns"""
        tensors = self.get_all_gpu_tensors()
        
        # Group by shape and dtype
        tensor_groups = defaultdict(list)
        for tensor in tensors:
            key = (tensor['shape'], tensor['dtype'])
            tensor_groups[key].append(tensor)
        
        print(f"\n{'='*60}")
        print(f"POTENTIAL MEMORY LEAKS - Rank {self.rank}")
        print(f"{'='*60}")
        
        suspicious_groups = []
        for (shape, dtype), group in tensor_groups.items():
            if len(group) > 5:  # More than 5 tensors with same shape/dtype
                total_size = sum(t['size_mb'] for t in group)
                suspicious_groups.append((shape, dtype, len(group), total_size))
        
        suspicious_groups.sort(key=lambda x: x[3], reverse=True)  # Sort by total size
        
        if suspicious_groups:
            print("Suspicious tensor groups (many tensors with same shape):")
            print(f"{'Shape':<25} {'DType':<10} {'Count':<6} {'Total MB'}")
            print("-" * 60)
            for shape, dtype, count, total_size in suspicious_groups[:10]:
                print(f"{str(shape)[:23]:<25} {str(dtype):<10} {count:<6} {total_size:.2f}")
        else:
            print("No obvious memory leaks detected.")
    
    def monitor_function_call(self, func, *args, **kwargs):
        """Monitor memory during function execution"""
        print(f"\n--- Monitoring function: {func.__name__} ---")
        
        # Before
        before_tensors = len(self.get_all_gpu_tensors())
        before_memory = torch.cuda.memory_allocated() / 1e6
        self.print_gpu_tensor_report(top_n=5)
        
        try:
            # Execute function
            result = func(*args, **kwargs)
            
            # After
            after_tensors = len(self.get_all_gpu_tensors())
            after_memory = torch.cuda.memory_allocated() / 1e6
            
            print(f"\n--- After {func.__name__} ---")
            print(f"Tensor count change: {before_tensors} -> {after_tensors} ({after_tensors-before_tensors:+d})")
            print(f"Memory change: {before_memory:.2f} -> {after_memory:.2f} MB ({after_memory-before_memory:+.2f} MB)")
            
            if after_tensors > before_tensors + 10:  # More than 10 new tensors
                print("WARNING: Significant tensor increase detected!")
                self.find_memory_leaks()
            
            return result
            
        except RuntimeError as e:
            if "out of memory" in str(e):
                print(f"\n!!! OOM ERROR in {func.__name__} !!!")
                print("GPU state at time of OOM:")
                self.print_gpu_tensor_report(top_n=10)
                self.find_memory_leaks()
                self.print_memory_fragmentation()
            raise e
    
    def print_memory_fragmentation(self):
        """Print memory fragmentation details"""
        if torch.cuda.is_available():
            print(f"\n{'='*60}")
            print(f"MEMORY FRAGMENTATION ANALYSIS")
            print(f"{'='*60}")
            
            # Get memory stats
            stats = torch.cuda.memory_stats()
            
            print(f"Allocated memory: {stats.get('allocated_bytes.all.current', 0) / 1e6:.2f} MB")
            print(f"Reserved memory: {stats.get('reserved_bytes.all.current', 0) / 1e6:.2f} MB")
            print(f"Active memory: {stats.get('active_bytes.all.current', 0) / 1e6:.2f} MB")
            print(f"Inactive memory: {stats.get('inactive_split_bytes.all.current', 0) / 1e6:.2f} MB")
            
            # Fragmentation indicator
            allocated = stats.get('allocated_bytes.all.current', 0)
            reserved = stats.get('reserved_bytes.all.current', 0)
            fragmentation = (reserved - allocated) / 1e6 if reserved > 0 else 0
            
            print(f"Fragmentation: {fragmentation:.2f} MB")
            
            if fragmentation > 1000:  # More than 1GB fragmented
                print("WARNING: High memory fragmentation detected!")
                print("Consider using torch.cuda.empty_cache() more frequently")

# Context manager for automatic monitoring
@contextmanager
def monitor_gpu_memory(inspector, operation_name, enabled):
    """Context manager to monitor GPU memory around operations"""
    if enabled:
        print(f"\n=== Starting {operation_name} ===")
        
        before_tensors = len(inspector.get_all_gpu_tensors())
        before_memory = torch.cuda.memory_allocated() / 1e6
        
        try:
            yield
        except RuntimeError as e:
            if "out of memory" in str(e):
                print(f"\n!!! OOM in {operation_name} !!!")
                inspector.print_gpu_tensor_report(top_n=10)
                inspector.find_memory_leaks()
                inspector.print_memory_fragmentation()
            raise e
        finally:
            after_tensors = len(inspector.get_all_gpu_tensors())
            after_memory = torch.cuda.memory_allocated() / 1e6
            
            print(f"=== Finished {operation_name} ===")
            print(f"Tensor count: {before_tensors} -> {after_tensors} ({after_tensors-before_tensors:+d})")
            print(f"Memory: {before_memory:.2f} -> {after_memory:.2f} MB ({after_memory-before_memory:+.2f} MB)")
    else:
        yield

# Einfachere Version für schnelle Diagnose:
def quick_gpu_diagnosis():
    """Schnelle GPU-Diagnose ohne komplexes Tracking"""
    
    def print_tensors():
        tensors = []
        for obj in gc.get_objects():
            if isinstance(obj, torch.Tensor) and obj.is_cuda:
                size_mb = obj.numel() * obj.element_size() / 1e6
                tensors.append((size_mb, obj.shape, obj.dtype, obj.requires_grad))
        
        tensors.sort(reverse=True)  # Largest first
        
        print(f"GPU Tensors: {len(tensors)} total")
        print(f"Top 10 largest:")
        for i, (size, shape, dtype, grad) in enumerate(tensors[:10]):
            print(f"  {i+1}. {size:.2f}MB - {shape} - {dtype} - grad:{grad}")
        
        total_size = sum(t[0] for t in tensors)
        print(f"Total tensor size: {total_size:.2f}MB")
        return tensors
    
    print("QUICK GPU DIAGNOSIS:")
    return print_tensors()